data:
  id: PANCANCER_PRI_MET
  params:
    data_dir: /lustre/hdd/LAS/weile-lab/howlader/Graph_Transformer/data_tcga/pan_meta_pri
    labels_filename: patient_labels.csv
    random_state: 42
    selected_genes_filename: /lustre/hdd/LAS/weile-lab/howlader/GraphPath/p_net_data/tcga_prostate_expressed_genes_and_cancer_genes.csv
    test_size: 0.1
    val_size: 0.1111111111111111
    zscore_cnv: true
  type: brca
models:
  id: P-net_PANCANCER_PRI_MET
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: null
    fitting_params:
      batch_size: 16
      class_weight: auto
      debug: false
      early_stop: true
      epoch: 200
      lr: 0.0001
      max_f1: true
      monitor: val_o6_f1
      n_outputs: 6
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: true
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: PANCANCER_PRI_MET
        params:
          data_dir: /lustre/hdd/LAS/weile-lab/howlader/Graph_Transformer/data_tcga/pan_meta_pri
          labels_filename: patient_labels.csv
          random_state: 42
          selected_genes_filename: /lustre/hdd/LAS/weile-lab/howlader/GraphPath/p_net_data/tcga_prostate_expressed_genes_and_cancer_genes.csv
          test_size: 0.1
          val_size: 0.1111111111111111
          zscore_cnv: true
        type: brca
      dropout:
      - 0.2
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 7
      - 20
      - 54
      - 148
      - 400
      n_hidden_layers: 5
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 10
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.9588014981,"1":0.9588014981,"2":0.9588014981,"3":0.96,"4":0.96,"5":0.96,"6":0.9675,"7":0.96,"8":0.96,"9":0.95875},"precision":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":1.0,"7":0.0,"8":1.0,"9":0.0},"auc":{"0":0.9477193813,"1":0.9104324495,"2":0.9149700126,"3":0.9267578125,"4":0.9130859375,"5":0.9361572266,"6":0.9260660807,"7":0.9108479818,"8":0.8760222828,"9":0.9357591561},"f1":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":0.3157894737,"7":0.0,"8":0.0588235294,"9":0.0},"f1_macro":{"0":0.4894837476,"1":0.4894837476,"2":0.4894837476,"3":0.4897959184,"4":0.4897959184,"5":0.4897959184,"6":0.6495720736,"7":0.4897959184,"8":0.519194651,"9":0.4894703255},"aupr":{"0":0.6150337769,"1":0.5193121982,"2":0.4825446021,"3":0.4594892014,"4":0.3311957338,"5":0.5395758095,"6":0.6625133422,"7":0.5513086616,"8":0.5005772741,"9":0.553276999},"recall":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":0.1875,"7":0.0,"8":0.0303030303,"9":0.0}}'
scores_mean: '{"accuracy":0.9602654494,"precision":0.2,"auc":0.9197818321,"f1":0.0374613003,"f1_macro":0.5085871966,"aupr":0.5214827599,"recall":0.021780303}'
scores_std: '{"accuracy":0.0026123018,"precision":0.4216370214,"auc":0.019838802,"f1":0.0995264951,"f1_macro":0.0504005977,"aupr":0.0899873564,"recall":0.0590016079}'
